### ISSUE TITLE
compilation erros found when c synthesis.

### ISSUE THREAD

**Issue by rainhard** [mmxsrup/bitonic-sort#1]
tried on vivado hls 2019.1,  c synthesis failed

```
ERROR: [HLS 200-70] Compilation errors found: In file include from bitonic-sort-master/hls/swap.cpp:1
bitonic-sort-master/hls/swap.cpp:6:8 error no member named 'swap' in namespace 'std'
  std::swap(data1, data2);
  ~~~~~^
bitonic-sort-master/hls/swap.cpp:6:8 error no member named 'swap' in namespace 'std'
  std::swap(data1, data2);
  ~~~~~^
```

does it not work, or i miss something?
thanks.

**Comment by mmxsrup** [comment]
Thanks for reporting the issue. I'm sorry for the late reply. 
Perhaps by using vivado-hls 2018.2, it was working fine. 
I think we can solve it by doing a swap without using `std::swap`. I will fix it.
